INSERT INTO product (product_name, price, stock)
VALUES
    ('Flower Decor Face Covering Chain',2.50,53),
    ('Lace Up Bodycon Skirt',7.25,53),
    ('High Waist Twist Front Shorts',8.99,5),
    ('ROMWE Sweetness Cherry Lace Cami Top',7.00,96),
    ('Cut Out Criss Cross One Piece Swimsuit',9.50,68),
    ('Tie Backless Halter Triangle V-string Bikini Swimsuit',10.49,84),
    ('Solid Tie Side Cover Up Skirt',4.49,14),
    ('ROMWE PUNK Tie Dye & Letter Graphic Notched Neck Bell Sleeve Crop Tee',6.99,78),
    ('O-ring Detail Halter Knot Side Triangle Thong Bikini Swimsuit',11.49,46),
    ('Bow & Bead Decor Face Covering Chain',2.80,98),
    ('SHEIN ICON Buckle Tape Cut Out Lace Up Bootcut Pants',8.00,12),
    ('ROMWE PUNK Grunge High Waist Floral & Baroque Print Lettuce Trim Skirt',8.00,12),
    ('Paperbag Waist Wide Leg Pants',14.49,21),
    ('Contrast Mesh Cut Out Halter One Piece Swimsuit',12.49,59),
    ('Color Block Triangle Thong Bikini Swimsuit',11.49,17),
    ('Split Thigh Cover Up',13.49,79),
    ('ROMWE Eyelet Embroidery Cami',4.50,47),
    ('Bikinx Rib Triangle High Cut Bikini Swimsuit',10.49,81),
    ('ROMWE Kawaii Bow Decor Face Covering',2.10,90),
    ('SHEIN Slant Pocket Belted PU Leather Pants',10.25,69),
    ('Geo Print Wide Waistband Biker Shorts',6.49,39),
    ('ROMWE Fairycore Drawstring Waist Tartan Skirt',11.49,9),
    ('Glitter Lace Up Plunging One Piece Swimsuit',9.99,2),
    ('Hollow Out Cover Up Dress',19.99,41),
    ('ROMWE PUNK Letter Graphic Crop Tee',4.28,42),
    ('Bikinx Floral Print Triangle Bikini Swimsuit',10.49,41),
    ('3pack Dalmatian Triangle Bikini Swimsuit & Cover Up',12.99,95),
    ('Star Decor Face Covering Chain',2.60,17),
    ('SHEIN Mulvari Lace Up 2 In 1 Pants',10.00,20),
    ('DAZY High Waist Pleated Hem Skirt',18.49,88),
    ('ROMWE Sweetness Floral Lace Cami Top',8.00,26),
    ('Split Thigh Cover Up Dress',14.00,21),
    ('Faux Pearl Decor Knot Side Sheer Cover Up Skirt Without Bikini',4.00,20),
    ('ROMWE Floral Appliques Lace Cami Top',5.75,83),
    ('Plant Print Tie Side Bikini Swimsuit',11.49,6),
    ('Heart Decor Face Covering Chain',2.50,55),
    ('Drawstring Waist Tie Back Pants',6.25,98),
    ('DAZY High Waist Split Thigh Skirt',13.49,89),
    ('ROMWE Skull Print Tank Top',5.18,44),
    ('Leopard Criss Cross One Piece Swimsuit',8.49,43),
    ('Eyelet Embroidery Pompom Cover Up',15.49,35),
    ('ROMWE Jacquard Ruffle Hem Appliques Cami',4.99,17),
    ('Halter Triangle Tie Side Bikini Swimsuit',4.99,18),
    ('Butterfly Decor Face Covering Chain',2.60,61),
    ('SHEIN SXY Lace Up High Waist Skirt',6.50,58),
    ('Patch Pocket Push Buckle Belted Wind Joggers',11.49,80),
    ('ROMWE PUNK Reflective Skeleton Print Crop Tee & Biker Shorts',6.75,69),
    ('Striped Triangle Bikini Swimsuit',8.50,45),
    ('Colorblock Wrap Bikini Swimsuit',12.49,47),
    ('Plain Drawstring Cover Up Dress',10.00,77),
    ('SHEIN EZwear Wings Pattern Short Sleeve Tee',6.00,78),
    ('Smocked Triangle Bikini Swimsuit With Beach Skirt',12.49,89),
    ('3pack Halter Triangle Bikini Swimsuit & Geo Print Kimono',17.00,90),
    ('Solid Face Covering',2.60,46),
    ('SHEIN High Waist Sequin Flare Leg Pants',13.75,73),
    ('Cut Out Lace Insert Biker Shorts',6.49,33),
    ('ROMWE Fairycore Floral Embroidery Lace Up Cami Top',9.00,61),
    ('Bikinx Floral Cut Out Criss Cross One Piece Swimsuit',12.99,20),
    ('Shirred Ruffle Hem Bandeau Cover Up',13.49,55),
    ('ROMWE Appliques Ribbed Halter Top',3.50,91),
    ('Floral Print Smocked Halter Bikini Swimsuit',11.99,95),
    ('Bow Decor Face Covering Chain',2.60,19),
    ('Ruffle Hem Wide Leg Shorts',6.50,11),
    ('High Waist Zip Side Ruffle Trim Skort',11.49,59),
    ('ROMWE PUNK Drawstring Waist Flap Pocket Wide Leg Parachute Pants',6.00,46),
    ('3pack Plain Criss Cross Halter Bikini Swimsuit & Cover Up Pants',14.49,94),
    ('Solid Open Front Kimono',10.49,21),
    ('ROMWE PUNK Grunge Floral & Slogan Graphic Crop Tee',4.00,51),
    ('Allover Print Halter Triangle Bikini Swimsuit With Cover Up',17.49,27),
    ('3pack Rhinestone Studded Halter Bikini Swimsuit & Beach Skirt',13.49,42),
    ('Solid Face Covering',1.00,63),
    ('SHEIN Split Hem Flare Leg Wave Striped Pants',7.00,91),
    ('Tropical Print Triangle Bikini Swimsuit With Cover Up',14.49,53),
    ('SHEIN EZwear Letter Graphic Elastic Waist Shorts',8.49,35),
    ('ROMWE 3pack Solid Bikini Swimsuit With Beach Skirt',8.50,73),
    ('Marble Print Underwire Push Up One Piece Swimsuit',16.00,6),
    ('Bikinx Random Floral Sweetheart Neck Cover Up Top Without Bikini',9.99,83),
    ('ROMWE Floral Pattern Contrast Binding Knit Top',6.00,86),
    ('Plain Halter Triangle Bikini Swimsuit',11.49,87),
    ('Cake Decor Face Covering Chain',2.60,21),
    ('SHEIN X VICTOR VON SCHWARZ Split Hem Flare Leg Pants',14.00,79),
    ('Swiss Dot Drawstring Side Ruffle Hem Ruched Bodycon Skirt',7.49,1),
    ('ROMWE STPL Striped Button Crop Cami',3.99,77),
    ('Criss Cross One Piece Swimsuit',12.00,13),
    ('Slit Thigh Crochet Cover Up',10.99,63),
    ('ROMWE PUNK Grunge Floral Print Crop Tee',6.49,86),
    ('3pack Plain Halter Triangle Bikini Swimsuit & Cover Up',14.49,83),
    ('Solid Face Covering',2.30,97),
    ('SHEIN Mulvari Elastic Waist Floral Print Wide Leg Pants',7.25,51),
    ('SHEIN X Kovid Kapoor Graphic Print Split Thigh Skirt',10.99,45),
    ('ROMWE Street Life Solid Cargo Joggers',7.42,8),
    ('Textured Crisscross Cut Out One Piece Swimsuit & Sheer Mesh Beach Skirt',13.99,85),
    ('Textured Halter Triangle Bikini Swimsuit',7.50,57),
    ('Fishnet overlay Split Cover Up',14.99,68),
    ('ROMWE X Tiggtactoe Letter Frog Graphic Drop Shoulder Tee',9.00,20),
    ('Floral Print Halter Bikini Swimsuit',10.99,54),
    ('Flower Decor Face Covering Chain',2.60,10),
    ('SHEIN X VOON Slant Pocket Wide Leg Shorts',7.75,62),
    ('Frill Trim Halter Triangle Tie Side Bikini Swimsuit',6.49,20),
    ('High Waist Fold Pleated Shorts',5.75,30),
    ('ROMWE PUNK Floral Print Lettuce Trim Mesh Skirt',9.49,15),
    ('Criss Cross Triangle Tie Side Bikini Swimsuit',9.49,17),
    ('Hollow Out Drawstring Side Cover Up',12.00,89),
    ('ROMWE Floral Embroidery Contrast Lace Crop Cami',4.75,49),
    ('Plain Halter Bikini Swimsuit',5.50,83),
    ('Cartoon Bear Decor Face Covering Chain',2.60,73),
    ('SHEIN X EMILY REED Contrast Mesh High Waist Pants',24.00,27),
    ('SHEIN Frenchy Swiss Dot Wide Leg Pants',13.49,21),
    ('ROMWE Goth Solid Flounce Sleeve Halter Top',8.49,10),
    ('Mesh Insert Twist Front One Piece Swimsuit',15.99,43),
    ('Hollow Out Drop Shoulder Cover Up Without Bikini',12.49,75),
    ('ROMWE Goth Floral & Wings Print Tee',6.99,27),
    ('O-ring Detail Halter Triangle Thong Bikini Swimsuit',8.49,40),
    ('Hollow Out Fuzzy Face Covering',2.30,35),
    ('Wave Print High Waist Straight Leg Pants',10.00,26),
    ('SHEIN ICON Bikercore Geo Print Lace Up Front Shorts',6.99,68),
    ('ROMWE X GOLDENLINE Car Letter Graphic Ribbed Tank Top',6.00,18),
    ('Cut Out One Piece Swimsuit',10.99,59),
    ('Patched Pocket Roll Up Sleeve Cover Up',13.49,33),
    ('ROMWE Solid Lace Up Knit Halter Top',5.00,59),
    ('Floral Print Smocked Halter Triangle Bikini Swimsuit',11.99,57),
    ('Heart Decor Face Covering Chain',2.50,14),
    ('Criss Cross Tie Back Mini Bodycon Skirt',5.75,94),
    ('Leopard Print Fringe Trim Asymmetrical Hem Skirt',11.49,12),
    ('ROMWE Geo Pattern Drop Shoulder Sweater',15.49,44),
    ('ROMWE X Gabiciamp Halter Drawstring One Piece Swimsuit',9.68,2),
    ('Plain Ruffle Hem Kimono',12.49,89),
    ('ROMWE PUNK Grunge Tie Dye Bodycon Dress',7.49,87),
    ('Lettuce Trim Rhinestone Decor Halter Triangle Bikini Swimsuit',14.00,56),
    ('Butterfly & Candy Decor Beaded Face Covering Chain',2.70,23),
    ('Polka Dot Print Flare Leg Pants',6.75,13),
    ('Ditsy Floral Frill Trim Ruffle Hem Skirt',11.00,77),
    ('ROMWE X POMOi Slogan Skeleton Graphic Sweatshirt',9.74,50),
    ('Plain Plunging Neck Belted One Piece Swimsuit',11.99,70),
    ('EMERY ROSE Tropical Print Contrast Lace Batwing Sleeve Kimono',11.49,39),
    ('ROMWE PUNK Grunge Heart And Floral Print Crop Tee',5.98,14),
    ('Plain Bikini Swimsuit',7.99,81),
    ('Color Block Beaded Face Covering Chain',2.50,46),
    ('SHEIN BAE Buckle Split Hem Pleated Skirt',9.00,12),
    ('SHEIN EZwear Letter Graphic Contrast Binding Dolphin Shorts',7.00,58),
    ('ROMWE PUNK Grunge Striped Pattern Space Dye Trumpet Sleeve Sweater',13.28,18),
    ('Bikinx Floral Print Lace Trim Criss Tie Side Bikini Set',12.49,51),
    ('Sheer Embroidered Mesh Tie Front Kimono',13.99,96),
    ('ROMWE Allover Floral Print Shirred Halter Top',4.50,38),
    ('ROMWE Grunge Punk Skull Rhinestone Triangle Halter Bikini Top',6.49,81),
    ('Bear & Flower Charm Face Covering Chain',2.60,70),
    ('SHEIN SXY High Waist Leopard & Marble Print Ruched Split Hem Pants',6.75,59),
    ('SHEIN BAE Zebra Striped Twist Front Split Thigh Flannelette Skirt',16.99,19),
    ('ROMWE PUNK Grunge Tie Dye Floral Print Trumpet Sleeve Dress',9.00,14),
    ('SHEIN Plain Criss Cross Bikini Swimsuit With Beach Skirt',16.00,69),
    ('Solid Button Front Kimono',14.49,33),
    ('ROMWE X 23Yueliang Cartoon Cat & Moon Graphic Tee',8.00,31),
    ('Triangle Tie Side Bikini Swimsuit',8.99,20),
    ('Rhinestone Eye Decor Face Covering',2.40,79),
    ('SHEIN BIZwear High Waist Skinny Pants',7.75,84),
    ('SHEIN Split Hem Allover Pants',4.75,81),
    ('Tie Front Roll Up Hem Shorts',10.99,4),
    ('ROMWE Mushroom & Frog Pattern Button Front Pocket Cardigan',12.99,82),
    ('Crisscross Knot Plunging One Piece Swimsuit',11.00,55),
    ('Striped Slit Thigh Cover Up',11.00,64),
    ('Floral Lace Triangle Bikini Swimsuit With Beach Skirt',13.49,37),
    ('ROMWE Contrast Lace Cami',4.00,4),
    ('Mesh Trim Triangle High Waisted Bikini Swimsuit',6.00,33),
    ('Solid Fuzzy Face Covering',2.60,60),
    ('SHEIN X Cecile Betbeze Drawstring Waist Contrast Binding Split Hem Pants',10.00,78),
    ('SHEIN VCAY Ditsy Floral Print Wide Leg Shorts',6.99,1),
    ('ROMWE PUNK Grunge Tie Dye Print Split Thigh Dress',8.49,34),
    ('Plain Cross Back One Piece Swimsuit',8.99,13),
    ('SHEIN Solid Sheer Beach Pants',6.49,70),
    ('ROMWE X Beereckless Cartoon Frog Graphic Crop Halter Top',6.49,18),
    ('Bikinx Zebra Stripe High Cut Bikini Swimsuit',9.99,66),
    ('3pack Solid Triangle Bikini Swimsuit & Drawstring Cover Up',13.49,39),
    ('2pcs Simple Face Covering Chain',1.50,26),
    ('Tropical Print Halter Triangle Bikini Top',4.38,94),
    ('High Waist Contrast Fish Net Shorts',6.00,73),
    ('SHEIN VCAY Ditsy Floral Print Split Thigh Skirt',12.49,49),
    ('ROMWE Fairycore Pom Pom Cable Knit Skirt',10.99,49),
    ('Ruched Tie Side Bikini Swimsuit',8.00,62),
    ('Sheer Cover Up Pants Without Bikini',15.49,60),
    ('ROMWE PUNK Grunge Cut Out Front Bodycon Dress',7.49,16),
    ('Ring Linked Harness Triangle Bikini Swimsuit',6.00,2),
    ('Zebra Stripe Smocked Halter Triangle Tie Side Bikini Swimsuit',11.49,44),
    ('Solid Fuzzy Face Covering',2.60,38),
    ('MOTF PREMIUM STRAIGHT FIT BUTTON HEM PANTS',23.00,72),
    ('SHEIN SXY Solid High Waist Bodycon Skirt',6.49,2),
    ('ROMWE Solid Lace Trim Halter Top',6.49,39),
    ('Solid Lace-up Back Bikini Swimsuit',11.49,18),
    ('Tie Shoulder Backless See Through Cover Up',9.49,85),
    ('ROMWE Grunge Punk Skeleton Mesh Cami Top',6.49,59),
    ('Sequin Fringe Trim Halter Triangle Bikini Swimsuit With Beach Skirt and Arm Sleeve',13.68,99),
    ('2pcs Minimalist Face Covering Chain',1.50,95),
    ('SHEIN Unity Button Detail Wrap Skirt',10.00,46),
    ('SHEIN EZwear Tartan Print Drawstring Waist Wide Leg Pants',13.99,26),
    ('ROMWE STPL Hollow Out Crop Sweater',9.49,87),
    ('Ring Linked Criss Cross Halter One Piece Swimsuit',12.49,54),
    ('Striped Pattern Lace Up Back Cover Up Dress',14.00,3),
    ('ROMWE X Ashley Baxter Figure & Car Graphic Drop Shoulder Tee',9.00,52),
    ('Plain Halter Triangle Bikini Swimsuit',8.00,91),
    ('Heart Charm Face Covering Chain',1.50,50),
    ('SHEIN SXY Holographic Drawstring Waist Carrot Pants',9.00,60),
    ('DAZY High Waist Plicated Detail Pants',20.99,7),
    ('ROMWE PUNK Floral & Paisley Print Flounce Sleeve Mesh Bodycon Dress',8.18,92),
    ('Plain Criss Cross One Piece Swimsuit',12.99,84),
    ('Knitted Slit Thigh Cover Up',12.99,21),
    ('ROMWE PUNK Figure Graphic Ribbed Knit Tee',6.49,41),
    ('Cut Out Halter Triangle Bikini Swimsuit',11.49,1),
    ('Flower Decor Face Covering Chain',2.50,49),
    ('SHEIN X VALHALLA Fringe Trim PU Leather Shorts',7.25,52),
    ('SHEIN ICON Figure & Letter Graphic Flare Leg Pants',12.49,67),
    ('SHEIN VCAY Paisley Print Drawstring Front Ruffle Hem Skirt',7.99,98),
    ('Cut-out Backless One Piece Swimsuit',11.99,27),
    ('SHEIN Floral Print Lettuce Trim Sheer Cover Up Without Cami Top',4.00,29),
    ('ROMWE Colorblock Lace Up Halter Top',5.00,7),
    ('Leopard Print Stitch Detail Bikini Top',6.00,16),
    ('Plaid Pattern Floral Embroidered Face Covering',1.90,19),
    ('SHEIN X No?-Liam High Waist Slant Pocket Pants',8.75,41),
    ('DAZY High Waist Flap Pocket Side Cargo Skirt',15.49,59),
    ('Ditsy Floral Print Layered Hem Skirt',12.99,12),
    ('Contrast Binding Criss Cross One Piece Swimsuit',11.49,43),
    ('Solid Crop Cover Up',5.49,96),
    ('ROMWE Grunge Punk 2 In 1 Letter Graphic Tee',9.08,19),
    ('Striped Halter Tie Back Bikini Swimsuit',9.49,55),
    ('2pcs Minimalist Face Covering Chain',1.50,31),
    ('ROMWE X The Smurfs Halloween Two Tone Cartoon Graphic Shorts',5.25,95),
    ('Bikinx Floral Print Triangle Tie Side Bikini Swimsuit',9.49,36),
    ('SHEIN VCAY Ditsy Floral Print Split Thigh Belted Pants',12.99,78),
    ('SHEIN SXY Solid Biker Shorts',7.00,57),
    ('Drawstring Plunging Neck One Piece Swimsuit',12.00,13),
    ('Hollow Out Side Split Cover Up',7.48,81),
    ('ROMWE PUNK Grunge High Neck Tie Back Asymmetrical Hem Tank Top',5.49,40),
    ('Leopard Triangle Tie Side Bikini Swimsuit',10.00,30),
    ('Rhinestone Crown Decor Fuzzy Face Covering',2.40,56),
    ('SHEIN X Lindsey Kate High Waist Cross Detail Pants',7.25,88),
    ('High Waist Ruffle Trim Skirt',12.00,64),
    ('SHEIN Modely Contrast Binding Mermaid Hem Skirt',27.49,55),
    ('Cut-out One Piece Swimsuit With Beach Skirt',13.00,20),
    ('Tie Dye Belted Kimono',18.99,8),
    ('ROMWE Anime Contrast Lace Tank Top',6.00,57),
    ('Allover Print Halter Triangle Bikini Swimsuit With Beach Skirt',12.99,87),
    ('Rhinestone Crown Decor Fuzzy Face Covering',2.40,94),
    ('SHEIN X (in)SALT-Y(d) High Waist Striped Print Hanky Hem Belted Skirt',13.25,26),
    ('SHEIN VCAY Floral Print Paperbag Waist Belted Shorts',7.99,30),
    ('High Waist Plicated Detail Wide Leg Shorts',11.99,41),
    ('Random Coral Print Criss Cross Tie Front One Piece Swimsuit',8.00,12),
    ('Flounce Sleeve Ruffle Hem Kimono',8.49,64),
    ('ROMWE PUNK Grunge Slogan Graphic Bell Sleeve Lettuce Trim Tee',6.48,20),
    ('Appliques Halter Triangle Tie Side Bikini Swimsuit',11.49,63),
    ('Solid Face Covering',1.50,79),
    ('Plain Halter Bikini Swimsuit',11.00,14),
    ('MOTF PREMIUM FLOWY WIDE LEG PANTS',17.99,18),
    ('SHEIN ICON Bikercore Letter Graphic Flap Pocket Side Drawstring Waist Cargo Pants',21.99,27),
    ('Button Fly Fold Pleated Wide Leg Shorts',9.99,12),
    ('Plunging Neck Criss Cross One Piece Swimsuit',11.49,50),
    ('Plain Drawstring Side Cover Up',8.10,25),
    ('ROMWE Goth Solid Flare Leg Jeans',15.50,8),
    ('3pack Allover Print Halter Triangle Bikini Swimsuit & Beach Skirt',12.49,97),
    ('Solid Beaded Face Covering Chain',1.70,91),
    ('SHEIN Tall High Waist Split Hem Bodycon Skirt',6.25,5),
    ('SHEIN SXY High Waist Flap Pocket Side Shorts',13.49,36),
    ('DAZY Slant Pocket PU Shorts',16.49,51),
    ('Contrast Mesh Crisscross One Piece Swimsuit',12.00,42),
    ('Solid Ripped Cover Up',5.30,89),
    ('ROMWE PUNK Rhinestone Skeleton Pattern Letter Graphic Crop Tee',7.99,28),
    ('Rhinestone Halter Triangle Tie Side Bikini Swimsuit',13.49,52),
    ('Faux Pearl & Bow Decor Face Covering Chain',1.50,88),
    ('SHEIN BAE High Waisted O-ring Cutout Flare Leg Pants',7.25,48),
    ('Floral Print Ruffle Trim Asymmetrical Hem Skirt',7.99,76),
    ('Ditsy Floral Tie Front Wide Leg Shorts',5.00,41),
    ('Color Block Criss Cross Ruched One Piece Swimsuit',8.99,83),
    ('Hollow Out Tie Front Cover Up Pants Without Bikini Panty',13.49,40),
    ('ROMWE STPL Striped High Neck Crop Sweater',10.99,73),
    ('Chinese Dragon Triangle Tie Side Bikini Swimsuit',10.49,68),
    ('Faux Pearl Decor Face Covering Chain',1.60,53),
    ('Heart Decor Letter Graphic Face Covering Chain',1.80,94),
    ('SHEIN ICON High Waist Mermaid Hem PU Skirt',19.49,94),
    ('Solid V Neck Tulip Hem Tee',7.49,35),
    ('SHEIN VCAY High Waist Flap Pocket Wide Leg Pants',11.00,87),
    ('High Waist Buckled Strap Wrap Hem Skirt',8.05,33),
    ('SHEIN Unity Heart Buttoned Ruched Split Thigh Skirt',9.50,58),
    ('Oil Painting & Slogan Graphic Drawstring Thermal Lined Hoodie',10.99,40),
    ('SHEIN X Firefall Strawberry Print Zipper Back Flare Skirt',6.50,39),
    ('SHEIN BAE Chain Detail Grommet Lace Up Satin Bodycon Skirt',7.50,66),
    ('2pcs Heart Pattern Face Covering',1.90,55),
    ('5pcs Solid Face Covering Chain',2.50,37),
    ('Patch Pocket Push Buckle Belted Wind Joggers',10.99,82),
    ('Swiss Dot One Shoulder Chiffon Dress',16.00,6),
    ('SHEIN X Sayndo Drawstring Slit Ruffle Hem Velvet Pants',8.25,88),
    ('Textured Shirred Skirt',7.50,88),
    ('SHEIN Modely Button Detail Flare Leg Pants',17.49,9),
    ('Bow Side Straight Leg Shorts',7.25,74),
    ('Tie Shoulder Peplum Cami Knit Top',9.99,48),
    ('SHEIN High Waist Plicated Slit Hem Pants',11.75,30),
    ('2pcs Rhinestone Decor Face Covering',1.70,93),
    ('2pcs Crystal Face Covering Chain',3.00,81),
    ('SHEIN VCAY Floral Print Tie Front Wide Leg Shorts',6.49,10),
    ('SHEIN SXY One Shoulder Mesh Panel Drawstring Top & Ruched Bodycon Skirt',19.99,62),
    ('SHEIN VCAY Polka Dot Print Drawstring Ruched Ruffle Hem Skirt',6.75,78),
    ('Random Allover Print Button Front Ruffle Hem Skirt',10.25,14),
    ('SHEIN High Waist Draped Wrap Skirt',8.50,91),
    ('Letter Graphic Kangaroo Pocket Drawstring Thermal Hoodie',9.99,77),
    ('SHEIN High Waist Carrot Pants',8.75,60),
    ('SHEIN Solid Button Front Wrap Skirt',6.25,98),
    ('SHEIN Mulvari High Waist Ombre Floral Appliques Skirt',10.75,11),
    ('3pcs American Football Pattern Face Covering',1.90,95),
    ('SHEIN Modely Contrast Tape Tassel Hem Wide Leg Pants',23.49,73),
    ('Faux Pearl Decor Face Covering Chain',2.30,70),
    ('SHEIN Asymmetrical Waist Shirred Back Zip Fly Shorts',5.50,14),
    ('Elastic Waist Slant Pocket Pants',14.99,85),
    ('Notched Neck Batwing Sleeve Twist Hem Blouse',7.49,57),
    ('Lace Panel Paisley Print Slit Skirt',5.50,57),
    ('SHEIN X VERO DIAZ Plaid Pearls Detail Tweed Skirt',17.50,76),
    ('DAZY Solid Button Front Crop Cardigan',14.99,58),
    ('Leopard Jacquard Tie Waist Satin Skirt',7.00,96),
    ('Solid Flap Pocket Side Cargo Pants',13.49,37),
    ('10pcs Solid Disposable Face Covering',1.80,8),
    ('2pcs Heart Decor Face Covering Chain',3.50,47),
    ('SHEIN BASICS Cotton Solid Capri Leggings',9.00,86),
    ('SHEIN VCAY Ruched Bust Backless Bandana Hem Crop Halter Top',6.48,12),
    ('High Waist Zip Detail Pants With Chain',9.25,19),
    ('SHEIN Drawstring Hem Ruched Spliced Skirt',5.25,5),
    ('Cartoon Graphic Thermal Lined Sweatshirt',10.49,45),
    ('High Waist Single Breasted Asymmetrical Hem Satin Skirt',6.50,85),
    ('SHEIN Modely Solid Wide Leg Pants',18.99,28),
    ('SHEIN High Waist Contrast Trim Corduroy Shorts',7.25,63),
    ('Polka Dot Face Covering',1.70,82),
    ('Color Block Beaded Face Covering Chain',2.10,15),
    ('SHEIN BAE Solid Knot Side Wrap Satin Skirt',16.49,10),
    ('SHEINNeu Tie Dye Split Hem Skirt',5.25,9),
    ('SHEIN VCAY High Waist Wrap Hem Skirt',11.58,11),
    ('Ombre Ruched Contrast Tape Skirt',7.00,24),
    ('SHEIN Tall Solid Flare Leg Pants',9.00,50),
    ('Letter Graphic Drop Shoulder Thermal Sweatshirt',4.00,51),
    ('Tie Shoulder PU Suspender Skirt',6.50,42),
    ('Faux Pearl Decor Face Covering Chain',1.90,82),
    ('Butterfly Decor Face Covering Chain',1.80,89),
    ('Guipure Lace Insert Ruffle Hem Wide Leg Pants Without Belt',22.49,49),
    ('SHEIN SXY Asymmetrical Neck Cut Out Front Mesh Top',11.49,63),
    ('Double Crazy Floral Print Split Hem Skirt',9.49,16),
    ('SHEIN Modely Floral Print Belted Tie Front Pants',8.50,88),
    ('SHEIN High Waist Gingham Split Pleated Hem Skirt',7.25,44),
    ('Letter Graphic Drop Shoulder Thermal Lined Sweatshirt',4.50,83),
    ('SHEIN X GottaBeJelly Hummingbird Print PU Leather Skirt',6.50,93),
    ('Rhinestone & Flower Decor Face Covering',2.10,67),
    ('3pcs Minimalist Face Covering Chain',4.00,8),
    ('SHEIN Floral Print Wrap Hem Skirt',9.50,96),
    ('SHEIN VCAY Tassel Trim Tie Front Shorts',8.00,78),
    ('Two Tone One Shoulder Batwing Sleeve Blouse',10.49,36),
    ('High Waist Solid Lace Skirt',8.50,42),
    ('Plaid Tie Front Tweed Skort',10.00,29),
    ('Two Tone One Shoulder Cut Out Crop Knit Top',7.00,43),
    ('evoluSHEIN High Waist Wrap Hem Wide Leg Pants',19.99,15),
    ('SHEIN VCAY Ditsy Floral Print Ruffle Trim Asymmetrical Skirt',10.00,99),
    ('Letter Graphic Face Covering',2.10,80),
    ('Colorful Face Covering Chain',2.30,5),
    ('Solid Split Back Pencil Skirt',23.99,74),
    ('Guipure Lace Insert Batwing Sleeve Blouse',11.49,74),
    ('Allover Floral Straight Leg Pants',8.00,27),
    ('MOTF PREMIUM EMBROIDERY MESH OVERLAY SKIRT',24.49,61),
    ('Cactus & Letter Graphic Thermal Lined Sweatshirt',8.99,100),
    ('SHEIN Floral Print Ruched Asymmetrical Mermaid Hem Skirt',6.75,22),
    ('SHEIN EZwear Drawstring Waist Flap Pocket Cargo Pants',16.99,67),
    ('Rhinestone American Flag Decor Face Covering',2.10,4),
    ('Faux Pearl & Butterfly Decor Face Covering Chain',2.40,39),
    ('Tropical Print Split Knot Hem Pants',10.99,70),
    ('SHEIN X BAW Collection Geo Print Ruffle Hem Split Hem PU Leather Skirt',6.25,34),
    ('SHEIN ICON Floral Print Drawstring Side Bandana Hem Tube Top',3.99,70),
    ('evoluSHEIN Allover Print Asymmetrical Hem Skirt',17.99,63),
    ('SHEIN VCAY Butterfly Print Knot Front Split Thigh Skirt',8.00,8),
    ('Pearls Beaded Cami Knit Top',8.49,62),
    ('DAZY Ruffle Hem Ditsy Floral Skirt',6.75,20),
    ('Color Block Beaded Face Covering Chain',2.10,58),
    ('2pcs Faux Pearl Decor Face Covering Chain',1.50,42),
    ('SHEIN EZwear Drawstring Waist Slant Pocket Parachute Pants',15.00,31),
    ('SHEIN EZwear Square Neck Split Thigh Dress',13.49,58),
    ('ROMWE PUNK Fire & Scroll Print Eyelet Buckled Detail Bodycon Skirt',10.25,25),
    ('SHEIN Ditsy Floral Scallop Edge Shorts',8.00,74),
    ('DAZY Tie Front Crop Cardigan',14.49,46),
    ('SHEIN VCAY Allover Print Hanky Hem Pleated Skirt',14.00,40),
    ('10pcs Heart Pattern Disposable Face Covering',1.90,25),
    ('Butterfly Charm Face Covering Chain',1.80,25),
    ('SHEIN Split Thigh PU Leather Skirt',6.75,83),
    ('Ditsy Floral Print Pleated Skirt',10.99,80),
    ('One Shoulder Ruffle Trim Split Thigh Belted Dress',16.99,44),
    ('Floral Embroidered Contrast Mesh Flare Skirt',7.50,63),
    ('High Waist Houndstooth Print Pleated Skirt',8.00,82),
    ('SHEIN VCAY Open Knit Single Button Cardigan',11.49,7),
    ('SHEIN Criss Cross Ruched Front Stirrup Leggings',5.50,61),
    ('2pcs Letter Graphic Face Covering',2.40,44),
    ('Beaded Face Covering Chain',1.80,79),
    ('SHEIN Tall High Waist Wide Leg Pants',16.49,15),
    ('Split Hem Wide Leg Pants',14.99,68),
    ('SHEIN ICON Cut Out Front Lace Cami Top',4.99,20),
    ('SHEIN High Waist PU Leather Pants',12.50,38),
    ('Floral Print Lace Insert Ruffle Hem Skirt',11.75,20),
    ('SHEIN VCAY Cut Out Wrap Cross Crop Knit Top',7.99,12),
    ('SHEIN X CLOUD BY CLAU Allover Cloud Print Fold Pleated Skort',6.50,16),
    ('Ruffle Trim Ruched Zip Back Suedette Bodycon Skirt',6.25,65),
    ('5pcs Heart Pattern Face Covering',2.10,82),
    ('Solid Face Covering Chain',1.80,85),
    ('SHEIN EZwear Camo Print Flap Pocket Cargo Pants',19.99,12),
    ('SHEIN VCAY Floral Print One Shoulder Flounce Sleeve Beach Blouse',5.99,34),
    ('Plaid Print Split Hem Twist Skirt',8.00,90),
    ('SHEIN Unity Paperbag Waist Belted Shorts',19.99,64),
    ('SHEIN SXY Flap Detail Fuzzy Hem Bodycon Skirt',5.75,78),
    ('Letter Graphic Zip Up Thermal Lined Drawstring Hoodie',14.49,45),
    ('Plaid Print Double Breasted Leggings',11.00,80),
    ('Heart & Letter Graphic Face Covering',1.70,40),
    ('Two Tone Face Covering Chain',2.20,83),
    ('Allover Print Split Thigh Skirt',14.00,36),
    ('SHEIN VCAY Solid Cami Top & Bodycon Skirt',4.99,51),
    ('SHEIN Lace Up Detail Flare Leg Pants',11.50,93),
    ('SHEIN SXY Tropical Print Shirred Layered Hem Skirt',5.00,81),
    ('DAZY Striped Pattern Knit Top',8.99,27),
    ('SHEIN High Waist Ditsy Floral Print Pants',9.25,41),
    ('Polka Dot Face Covering',1.70,72),
    ('Heart Decor Face Covering Chain',1.90,80),
    ('Ditsy Floral Wide Leg Pants',13.99,61),
    ('SHEIN BAE Twist Front Wrap Hem Solid Skirt',10.49,39),
    ('One Shoulder Cut Out Wrap Hem Metallic Dress',10.50,62),
    ('SHEIN Paisley Print Ruffle Hem Skirt',11.00,97),
    ('SHEIN Unity Allover Print Asymmetrical Hem Skirt',6.00,87),
    ('Butterfly & Slogan Graphic Drawstring Thermal Lined Hoodie',10.99,88),
    ('SHEIN X GD GRL BHVIOR Zebra Striped Mesh Insert Leggings',6.25,90),
    ('Two Tone Beaded Face Covering Chain',1.90,11),
    ('Colorblock Face Covering Chain',2.20,100),
    ('ROMWE PUNK Ripped Contrast Mesh Flare Leg Pants',14.99,89),
    ('SHEIN EZwear Solid Split Thigh Dress',11.49,98),
    ('Ladder Cut Out Suedette Skirt',5.50,78),
    ('Leather Look Asymmetrical Hem Skirt',6.75,18),
    ('Floral Print Drawstring Ruched Ruffle Hem Bodycon Skirt',5.00,85),
    ('DAZY Solid Ribbed Knit Top',11.99,50),
    ('SHEIN Unity Allover Print High Waist Straight Leg Pants',9.25,15),
    ('Two Tone Beaded Face Covering Chain',1.90,36),
    ('Letter & Heart Detail Beaded Face Covering Chain',2.00,94),
    ('10pcs Solid Face Covering Rope',3.10,97),
    ('SHEIN EZwear Solid Split Thigh Cami Dress',9.00,15),
    ('SHEIN VCAY Shirred Waist Chevron Pattern Frill Trim Skirt',8.25,3),
    ('ROMWE Ditsy Floral Slit Mini Skirt',5.00,44),
    ('Letter Graphic Kangaroo Pocket Drawstring Hoodie',12.99,87),
    ('Zip Waist ditsy Floral Skirt',10.25,49),
    ('10pcs Heart Pattern Face Covering',1.90,67),
    ('Letter & Faux Pearl Decor Face Covering Chain',1.50,1),
    ('6pcs Solid Face Covering Rope',2.40,44),
    ('One Shoulder Cut Out Drawstring Side Split Thigh Dress',15.00,32),
    ('Grommet Lace Up D-ring Belted Flare Leg Pants',12.50,13),
    ('SHEIN Unity Zipper Detail Solid Straight Skirt',6.00,23),
    ('Slogan Graphic Kangaroo Pocket Drawstring Thermal Hoodie',10.99,58),
    ('SHEIN SXY Self Belted Cut Out Patched Shorts',13.00,64),
    ('SHEIN BAE Twist Waist Flare Leg Pants',8.50,35),
    ('2pcs Camo Pattern Face Covering',2.10,25),
    ('Butterfly & Faux Pearl Decor Face Covering Chain',2.00,11),
    ('2pcs Color Block Face Covering Rope',1.70,93),
    ('SHEIN VCAY Solid Button Front Sleeveless Beach Shirt',8.99,33),
    ('Ruched Side Waffle Knit Bodycon Skirt',9.49,71),
    ('ROMWE Tie Dye Two Layered Hem Skirt',5.50,37),
    ('Ruffle Trim Cable Knit Top',10.49,85),
    ('Cut Out Knot Hem Leggings',6.25,23),
    ('Strawberry & Bead Decor Face Covering Chain',2.10,74),
    ('2pcs Minimalist Face Covering Chain',4.60,6),
    ('6pcs Color Block Face Covering Chain',2.10,83),
    ('SHEIN EZwear Solid Split Thigh Cami Dress',10.49,14),
    ('SHEIN 90s Solid Wrap Cross Tie Hem Pants',9.00,20),
    ('ROMWE Graphic Print Skirt',4.00,81),
    ('Slogan Graphic Thermal Lined Sweatshirt',10.49,48),
    ('Knot Detail Fringe Hem Guipure Lace Skirt',11.75,17),
    ('2pcs Solid Face Covering',1.70,50),
    ('Faux Pearl Decor Face Covering Chain',2.10,75),
    ('6pcs Color Block Face Covering Chain',2.10,49),
    ('One Shoulder Ruffle Trim Blouse',7.00,26),
    ('SHEIN X Huberlene Ruffle Trim Pleated Satin Wide Leg Pants',8.50,51),
    ('SHEIN SXY Fringe Trim Ruched Sequin Bodycon Skirt',9.50,19),
    ('Abstract Figure And Slogan Graphic Thermal Lined Sweatshirt',8.99,81),
    ('DAZY Cartoon Graphic Drawstring Sweatpants',7.50,77),
    ('SHEIN Shirred Layered Hem Skirt',7.00,100),
    ('2pcs Solid Face Covering',1.70,19),
    ('Color Block Beaded Face Covering Chain',1.80,58),
    ('Faux Pearl Decor Face Covering Chain',2.50,30),
    ('Eyelet Embroidery One Shoulder Belted Romper',14.99,41),
    ('SHEIN X LORI STEPHENSON Solid Split Side Shorts',6.00,74),
    ('ROMWE Plaid Belted Pleated Skirt',6.25,75),
    ('Solid Crop Tank Knit Top',8.49,5),
    ('Allover Print Draped Split Thigh Skirt',8.75,22),
    ('2pcs Tie Dye Face Covering',1.70,88),
    ('Heart Decor Face Covering Chain',1.50,49),
    ('Solid Split Hem Wide Leg Pants',18.49,7),
    ('Butterfly Decor Beaded Face Covering Chain',2.60,10),
    ('Cut Out Twist Front Cami Top',8.99,71),
    ('Allover Print Ruffle Hem Wrap Skirt',6.00,79),
    ('SHEIN X EBIB Graphic Print Side Seam Shorts',7.50,55),
    ('Drawstring Front Open Knit Sweater',15.49,79),
    ('High Waist Letter Patched 2 In 1 Leggings',10.00,39),
    ('7pcs Solid Face Covering',2.10,78),
    ('Faux Pearl Decor Face Covering Chain',1.90,16),
    ('Flower Decor Face Covering Chain',3.30,21),
    ('SHEINNeu Lace Up Side Wide Leg Shorts',8.75,52),
    ('Asymmetrical Neck Batwing Sleeve Tee',8.99,71),
    ('Allover Print Contrast Top-stitching Biker Shorts',4.75,61),
    ('ROMWE Plaid Lace Up Pleated Skirt',5.50,4),
    ('SHEIN Flap Pocket Side Cargo Skirt',12.25,81),
    ('DAZY Striped Pattern Contrast Collar Knit Top',11.99,10),
    ('Frill Trim Belted Shorts',12.99,40),
    ('90s Allover Print Button Front Raw Hem Shorts',9.00,60),
    ('7pcs Solid Face Covering',1.90,54),
    ('Flower & Star Decor Face Covering Chain',2.30,26),
    ('Dice Decor Face Covering Chain',2.20,81),
    ('SHEIN EZwear Allover Print Hanky Hem Tube Top',3.99,26),
    ('SHEIN X Eva Novielli Floral Print Leggings',5.75,81),
    ('ROMWE Solid Split Criss Cross Skirt',6.25,39),
    ('DAZY Slogan Graphic Drop Shoulder Oversized Sweatshirt',13.49,42),
    ('High Waist Polka Dot Slit Skirt',8.00,60),
    ('Heart & Letter Detail Face Covering Chain',2.10,73),
    ('Butterfly & Faux Pearl Decor Face Covering Chain',2.90,20),
    ('Color Block Beaded Face Covering Chain',2.30,39),
    ('Solid Asymmetrical Neck Petal Sleeve Blouse',7.99,58),
    ('SHEIN Zebra Striped Slant Pockets Wide Leg Pants',8.50,80),
    ('High Waist Jacquard Split Hem Belted Satin Skirt',8.00,87),
    ('DAZY Solid Drop Shoulder Pointelle Knit Sweater',14.49,55),
    ('SHEIN EZwear High Waist Slant Pocket Contrast Binding Suedette Wrap Skirt',9.00,99),
    ('SHEIN VCAY Allover Floral Print Paper Bag Waist Wide Leg Pants',9.49,34),
    ('2pcs Gingham Pattern Face Covering',2.10,28),
    ('Flower & Bead Decor Face Covering Chain',2.50,48),
    ('Flower Decor Beaded Face Covering Chain',2.40,92),
    ('SHEIN X Belle Mariano Solid Square Neck Tank Top',10.49,15),
    ('SHEIN Leaf Print Split Thigh Draped Skirt',11.50,38),
    ('ROMWE Heart & Geo Print Skirt',5.00,15),
    ('Floral & Letter Graphic Thermal Lined Sweatshirt',9.49,23),
    ('High Waist Ruched Leggings',8.00,96),
    ('2pcs Camo Print Face Covering',2.10,45),
    ('Bead & Faux Pearl Decor Face Covering Chain',2.50,80),
    ('SHEIN X Manic Pop Button Front Flap Pocket Skirt',9.00,83),
    ('Beaded Face Covering Chain',2.30,37),
    ('One Shoulder Cut Waist Puff Sleeve Dress',12.49,84),
    ('Solid Biker Shorts',4.75,35),
    ('SHEIN X Gabriella Mavri Abstract Print Mesh Maxi Skirt',12.00,77),
    ('Mushroom & Slogan Graphic Drawstring Thermal Lined Hoodie',10.99,78),
    ('SHEIN X Michelle Wong High Waist Belted Asymmetrical Hem Skirt',9.50,58),
    ('2pcs Rhinestone Heart Decor Face Covering',2.10,32),
    ('Flower & Rhinestone Decor Face Covering Chain',2.90,85),
    ('Rhinestone & Faux Pearl Decor Face Covering Chain',2.30,11),
    ('Eyelet Embroidery Twist Front Asymmetrical Hem Tee',9.49,39),
    ('SHEIN X Sara Cennamo Self Belted Split Satin Pants',10.50,41),
    ('ROMWE Ditsy Floral Ruffle Hem Skirt',5.75,35),
    ('Sculpture & Letter Graphic Thermal Lined Drawstring Hoodie',10.49,58),
    ('SHEIN BAE Rhinestone Detail Flare Leg Pants',17.99,76),
    ('SHEIN X Michelle Wong Flipped Waist Wide Leg Pants',10.75,75),
    ('Solid Breathable Face Covering',2.20,61),
    ('Evil Eye Decor Face Covering Chain',1.90,23),
    ('Butterfly Decor Beaded Face Covering Chain',2.30,23),
    ('Asymmetrical Neck Ruffle Trim Split Thigh Sequin Dress',47.99,19),
    ('SHEIN Cut Out Biker Shorts',4.25,76),
    ('SHEINNeu Ruffle Trim Jacquard Shorts',6.75,65),
    ('Knot Front Crop Cardigan',13.49,41),
    ('SHEIN SXY High Waist Lace Flare Leg Pants',9.25,80),
    ('Comic Print Face Covering',1.50,38),
    ('Bead Decor Face Covering Chain',2.30,64),
    ('Cherry Decor Beaded Face Covering Chain',2.20,4),
    ('SHEIN VCAY Paisley Print Tie Backless Bandana Hem Cami Top',5.99,24),
    ('SHEIN SXY Cut Out Waist Flare Leg Snakeskin Print Pants',6.75,56),
    ('ROMWE Cartoon Print Contrast Lace Layered Skirt',6.75,89),
    ('DAZY Tie Front Split Sleeve Cardigan',15.99,93),
    ('SHEIN Ruffle Detail Flare Leg Pants',8.00,33),
    ('Letter Graphic Kangaroo Pocket Drawstring Thermal Lined Hoodie',8.00,56),
    ('Asymmetrical Waist Split Hem Skirt',6.25,9),
    ('SHEIN MOD Lace Up Side PU Leather Skirt',16.49,43),
    ('Drop Shoulder Knot Front Crop Kimono',8.00,75),
    ('Two Layer Hem Shorts',8.50,90),
    ('DAZY Solid High Neck Drop Shoulder Oversized Sweater',36.00,93),
    ('MOTF PREMIUM VISCOSE SLINKY PANTS',34.99,85),
    ('DAZY High Waist Slant Pocket Skirt',18.99,88),
    ('Split Thigh Cover Up Skirt',10.00,22),
    ('High Waist Cut Out Drawstring Side Flare Leg Pants',7.50,98),
    ('Letter Graphic Kangaroo Pocket Drawstring Thermal Lined Hoodie',9.99,11),
    ('evoluSHEIN Flap Pocket Side Elastic Waist Cargo Pants',22.49,38),
    ('Pearls Beaded Split Hem Flare Leg Pants',15.99,80),
    ('Pom-pom Trim Split Side Cover Up Pants',9.00,54),
    ('SHEIN SXY Contrast Sequin Flare Leg Pants',11.00,91),
    ('Japanese Character And Floral Print Kangaroo Pocket Drawstring Thermal Hoodie',10.49,49),
    ('SHEIN X GOD.like High Waist Topstitching Pants',20.00,90),
    ('Geo Print Tassel Tie Waist Dual Pocket Pants',14.49,3),
    ('Open Front Kimono',10.49,100),
    ('Leopard Print Ruffle Trim Mesh Pants Without Panty',5.00,62),
    ('Slogan Graphic Thermal Lined Pullover',6.00,53),
    ('SHEIN Modely Tie Side Chain Detail Wrap Skirt',8.50,68),
    ('SHEIN BIZwear High Waist Split Hem Pants',12.99,15),
    ('Plain Backless Cover Up',12.00,3),
    ('Paperbag Waist Bow Detail Shorts',5.25,21),
    ('Heart & Slogan Graphic Kangaroo Pocket Drawstring Thermal Hoodie',9.99,83),
    ('SHEIN BAE Tie Dye Print Ruched Split Side Sequin Skirt',10.75,42),
    ('SHEIN EZwear High Waist Solid Shorts',4.99,78),
    ('Plant Print Semi Sheer Mesh Cover Up Set',13.00,93),
    ('SHEIN Cutout Slit Hem Solid Pants',7.25,3),
    ('Letter Graphic Thermal Lined Sweatshirt',8.49,52),
    ('Fold Pleated Slant Pocket Pants',11.50,37),
    ('Lace Up Front Solid Leggings',12.49,91),
    ('2pack Cover Up',7.49,60),
    ('SHEIN ICON High Waist Grommet Lace Up Side Bodycon Skirt',6.50,32),
    ('Slogan & Cartoon Graphic Kangaroo Pocket Drawstring Thermal Hoodie',10.49,52),
    ('Striped Elastic Waist Shorts',6.00,44),
    ('Faux Pearl Decor Frill Trim Triangle Bikini Top',5.49,39),
    ('Wide Waistband Fold Pleated Skirt',18.49,68),
    ('SHEIN Bell Sleeve Knot Front Crochet Kimono',6.49,4),
    ('Bow Side Split Hem PU Leather Skinny Pants',8.75,33),
    ('ROMWE Goth Striped Pattern Off Shoulder Crop Sweater',8.00,58),
    ('SHEIN Rainbow Striped Print Lace Up Flare Leg Pants',8.75,98),
    ('Patchwork Print Tie Side Bikini Swimsuit',6.25,95),
    ('Ruffle Hem Cover Up',8.49,89),
    ('Contrast Mesh Bodycon Skirt',5.75,69),
    ('Cartoon And Floral Print Thermal Lined Sweatshirt',8.99,35),
    ('SHEIN SXY Zip Up Plaid Tweed Bodycon Skirt',5.25,16),
    ('Ring Linked Halter Triangle Bikini Swimsuit With Beach Skirt',13.49,23),
    ('Hollow Out Cover Up Skirt Without Bikini',5.49,61),
    ('SHEIN X Michelle Wong Knot Side Paperbag Waist Split Hem Wide Leg Crop Pants',7.75,12),
    ('DAZY Slogan Graphic Drop Shoulder Sweatshirt',14.49,57),
    ('SHEIN SXY Floral Print Ruffle Trim Pants',7.75,2),
    ('Floral Print Halter Triangle Bikini Swimsuit With Cover Up',13.00,50),
    ('Contrast Lace Plunging Cover Up',14.99,99),
    ('SHEIN SXY Belted Zip Side Skort',6.75,39),
    ('Heart Print Kangaroo Pocket Drawstring Thermal Hoodie',9.99,42),
    ('SHEIN VCAY Elastic Waist Fold Pleated Tapered Pants',7.00,36),
    ('Floral Print Triangle Thong Bikini Swimsuit & Kimono',12.49,43),
    ('Sheer Tie Front Kimono',17.49,37),
    ('SHEIN High Waist Textured Split Hem Flare Leg Pants',7.25,58),
    ('Mock Neck Ribbed Knit Sweater',10.99,41),
    ('SHEIN Zip Up Straight Leg Pants',10.75,38),
    ('Floral Frill Trim Halter Triangle Bikini Swimsuit',10.49,70),
    ('Button Front Split Kimono',13.00,56),
    ('SHEIN MOD Rhinestone Detail Puff Hem Skirt',6.25,63),
    ('Letter Graphic Thermal Lined Sweatshirt',7.00,77),
    ('SHEIN Modely High Waist Plaid Fuzzy Trim Flare Leg Pants',12.00,95),
    ('Floral Print Halter Triangle Bikini Swimsuit',10.49,38),
    ('Colorblock Half Zip Drop Shoulder Sweatshirt',13.99,62),
    ('SHEIN Allover Print Zipper Fly Pants',7.50,52),
    ('Sunflower And Slogan Graphic Drop Shoulder Drawstring Hoodie',10.00,24),
    ('SHEIN Drawstring Hem Belted Pants',10.75,85),
    ('Metallic Halter Bikini Top',5.49,61),
    ('Mock Neck Flounce Sleeve Ruffle Hem Bodycon Dress',11.00,68),
    ('High Waist Allover Print Slit Hem Flare Leg Pants',9.25,64),
    ('Heart & Butterfly Print Thermal Pullover',8.49,35),
    ('SHEIN X CIRCE High Waist Snakeskin Print Wide Leg Shorts',4.75,37),
    ('4pack Fluid Pattern Halter Bikini Swimsuit & Beach Skirt & Kerchief',14.00,35),
    ('Slogan Embroidery Sweatshirt',11.49,88),
    ('SHEIN ICON Tie Dye Straight Leg Pants',6.00,34),
    ('Letter Graphic Contrast Collar Quarter Zip Thermal Lined Sweatshirt',11.99,15),
    ('SHEIN PETITE Plaid Print High Waist Wool-Mix Shorts',8.00,19),
    ('Faux Pearl Decor Triangle Bikini Swimsuit',10.49,70),
    ('Contrast Lace Batwing Sleeve Tee',11.49,3),
    ('Lace Up Front Contrast Binding Shorts',5.25,26),
    ('Butterfly & Letter Graphic Thermal Lined Sweatshirt',8.49,9),
    ('SHEIN BAE Snakeskin Print Split Hem Skinny Pants',10.00,29),
    ('Textured Lace Up Halter Triangle Tie Side Bikini Swimsuit',10.49,90),
    ('SHEIN MOD Drop Shoulder Heathered Knit Zip-Up Hoodie',12.00,49),
    ('SHEIN High Waist Flare Leg Pants',8.50,63),
    ('Paw & Heart Print Thermal Lined Sweatshirt',7.00,62),
    ('SHEIN Mulvari High Waist Tie Dye Wide Leg Pants',7.50,3),
    ('Plain Halter Triangle Bikini Swimsuit With Beach Skirt',14.49,34),
    ('V-back Lace Trim Bodycon Dress',15.00,66),
    ('SHEIN MOD Lace Up Front Wide Leg Shorts',8.50,68),
    ('SHEIN Frenchy Colorblock Drop Shoulder Sweater',22.49,90),
    ('Ring Linked Flare Leg Pants',9.00,43),
    ('Halter Triangle Bikini Swimsuit With Beach Skirt',12.49,50),
    ('Floral Print Keyhole Neckline Dress',13.99,95),
    ('Cut Out Knot Waist Flare Leg Pants',6.50,13),
    ('Vegetable And Letter Graphic Thermal Lined Sweatshirt',6.00,54),
    ('MOTF PREMIUM LYOCELL ASYMMETRICAL SKIRT',11.49,82),
    ('Floral Print Halter Triangle Bikini Top',6.00,17),
    ('Guipure Lace Insert Lantern Sleeve Dress',15.00,53),
    ('SHEIN Unity High Waist Tie Dye PU Leather Skirt',5.74,97),
    ('Mushroom Print Drawstring Thermal Lined Hoodie',10.49,50),
    ('SHEIN X Isabelle WANG High Waist Flare Leg Slant Pocket Pants',22.00,5),
    ('Zig Zag Binding Trim Halter Thong Bikini Swimsuit',11.25,25),
    ('SHEIN EZwear Ribbed Knit Button Front Crop Cardigan',13.00,65),
    ('SHEIN MOD Buttoned Front Allover Print Pants',9.00,64),
    ('Mona Lisa & Letter Graphic Thermal Lined Sweatshirt',8.00,4),
    ('SHEIN BIZwear High Waist Checker Print Split Hem Wide Leg Pants',8.50,48),
    ('3pack Floral Triangle Tie Side Bikini Swimsuit',9.50,28),
    ('Ripped Roll Up Hem Denim Shorts',15.00,86),
    ('Solid Wrap Detail Zipper Back Skirt',6.50,70),
    ('Leopard Pattern Turtleneck Drop Shoulder Sweater',20.00,8),
    ('SHEIN MOD Plaid Pattern Tweed Skirt',6.00,40),
    ('Appliques Halter Triangle Bikini Swimsuit With Beach Skirt',13.49,82),
    ('SHEIN BIZwear Lantern Sleeve Buckle Belted Dress',15.00,30),
    ('SHEIN X ANIHOUVI Ludmilla Contrast Side Seam Cut Out Waist Skinny Pants',13.25,14),
    ('Slogan Graphic Thermal Lined Drawstring Hoodie',9.99,49),
    ('SHEIN X GAUTII Mesh Insert PU Leather Flare Leg Pants With Belt',25.00,61),
    ('Zebra Stripe High Waisted Bikini Swimsuit',5.25,89),
    ('SHEIN Tall Floral Print Lettuce Trim Mock Neck Belted Dress',13.00,5),
    ('SHEIN BAE Cut-out Solid Skinny Cropped Pants',12.00,61),
    ('Heart And Letter Graphic Thermal Lined Sweatshirt',8.99,55),
    ('SHEIN High Waist Ditsy Floral Straight Leg Pants',12.25,42),
    ('Fluid Pattern Bikini Swimsuit',7.00,42),
    ('SHEIN EZwear Patch Detail Corduroy Overall Dress Without Tee',13.00,35),
    ('SHEIN Checker Print Straight Leg Pants',8.25,61),
    ('UFO And Letter Graphic Kangaroo Pocket Drawstring Thermal Hoodie',10.49,99),
    ('SHEIN Flap Pocket Tapered Pants',12.25,88),
    ('Scallop Trim Halter Triangle Tie Side Bikini Swimsuit',10.49,4),
    ('DAZY Slant Pocket Plicated Detail Suit Pants',14.00,74),
    ('SHEIN High Waist Slant Pocket Shorts',7.75,72),
    ('SHEIN Frenchy Bow Back Drop Shoulder Sweater',16.99,87),
    ('SHEIN Allover Print Velvet Wide Leg Pants',6.75,33),
    ('Contrast Sequin Triangle Tie Side Bikini Swimsuit',9.49,27),
    ('Solid Bishop Sleeve Blouse',11.00,63),
    ('High Waist Wide Leg Pants',8.00,18),
    ('Letter Graphic Kangaroo Pocket Drawstring Thermal Lined Hoodie',12.99,54),
    ('SHEIN X Maria Buffalo Plaid Print Pants With Marble Print Mesh Wrap Skirt',8.00,93),
    ('3pack Geo Color Block Lace Up Bikini Swimsuit & Cover Up Top',15.49,78),
    ('Houndstooth Ruffle Hem 2 In 1 Dress',15.00,90),
    ('SHEIN ICON Fuzzy Trim PU Shorts',10.00,3),
    ('Letter Graphic Thermal Lined Sweatshirt',10.49,46),
    ('Solid Drawstring Waist Pants',10.00,25),
    ('3pack Triangle Thong Bikini Swimsuit & Beach Skirt',12.99,65),
    ('SHEIN SXY Graphic Tie Backless Split Thigh Cami Dress',12.75,37),
    ('PU Lace Hem O-ring Zip-up Skirt',9.00,83),
    ('Skeleton And Slogan Graphic Kangaroo Pocket Thermal Lined Drawstring Hoodie',13.49,45),
    ('GAME OF THRONES | SHEIN Letter & Reindeer Print Flap Pocket Pants',8.75,8),
    ('Allover Print Halter Triangle Bikini Swimsuit',15.49,21),
    ('Drop Shoulder Shrug Cardigan',13.00,50),
    ('SHEIN X Season Lye Button Detail Wide Leg Pants',11.00,94),
    ('Leopard And Letter Graphic Thermal Lined Sweatshirt',9.49,2),
    ('SHEIN Frenchy Double Button Detail Flare Leg Corduroy Pants',7.50,26),
    ('Contrast Binding Triangle Thong Bikini Swimsuit',5.50,5),
    ('Cable Knit V Neck Drop Shoulder Sweater',12.00,76),
    ('ROMWE PUNK Solid PU Leather Flare Leg Pants',11.99,70),
    ('Random Letter Detail Beaded Face Covering Chain',2.60,94),
    ('Crystal Beaded Face Covering Chain',1.80,92),
    ('SHEIN EZwear Plaid Print Flare Leg Pants',12.99,50),
    ('Butterfly & Faux Pearl Decor Face Covering Chain',2.10,48),
    ('Bikinx Color Block Bikini Swimsuit',13.49,14),
    ('Random Tropical Print Contrast Mesh Bikini Swimsuit',10.49,51),
    ('Fish Scales Print Bikini Swimsuit With Cover Up',19.49,39),
    ('Bikinx Chain Linked Triangle Thong Bikini Swimsuit',10.99,36),
    ('SHEIN X SAAMU Colorblock Wide Leg Shorts',6.49,59),
    ('SHEIN ICON Contrast Stitch Buckle Belted Skirt',9.49,50),
    ('3pcs Solid Face Covering Chain',2.10,75),
    ('Bear Charm Face Coverings Chain',1.90,100),
    ('Crystal Beaded Face Covering Chain',1.80,17),
    ('SHEIN Frenchy High Waist Flare Leg Pants',10.00,58),
    ('7pcs Solid Face Covering',2.10,29),
    ('Floral Halter Triangle Bikini Swimsuit With Cover Up',14.49,35),
    ('Christmas Gift Patch Decor Face Covering',1.50,65),
    ('Striped Ruched One Piece Swimsuit',11.99,32),
    ('Tropical Print Halter Triangle Bikini Swimsuit With Cover Up',13.00,5),
    ('ROMWE Tie Dye Graphic Print Asymmetric Skirt',5.75,95),
    ('SHEIN EZwear Flap Pocket Cargo Skirt',14.49,37),
    ('Bead Decor Face Covering Chain',2.10,87),
    ('Flower & Four-leaf Clover Decor Face Covering Chain',2.00,2),
    ('Solid Knot Front Shorts',8.49,15),
    ('7pcs Solid Face Covering',2.10,99),
    ('3pack Fluid Pattern Halter Bikini Swimsuit & Bandana',10.49,65),
    ('Textured Criss Cross Bikini Top',7.00,57),
    ('Sequin Rabbit Ear & Bow Decor Face Covering',2.50,25),
    ('Applique Triangle Bikini Swimsuit',8.50,53),
    ('High Waist Metallic Slit Skirt',5.75,24),
    ('Ruched Split Thigh Skirt',11.99,100),
    ('10pcs Paw Pattern Face Covering',1.50,10),
    ('Christmas Tree Patch Decor Face Covering',1.50,20),
    ('Faux Pearl & Flower Decor Face Covering Chain',2.00,64),
    ('Christmas Santa Claus Patch Decor Face Covering',1.50,2),
    ('SHEIN EZwear Letter Graphic Drawstring Waist Shorts',9.49,14),
    ('3pcs Solid Face Covering',2.90,54),
    ('Lace Up Smocked Halter Bikini Swimsuit',12.00,99),
    ('Paisley Chevron Stripe Tape High Neck One Piece Swimsuit',10.99,33),
    ('Solid Knot Back Triangle Bikini Top',4.99,30),
    ('Pearl Beaded Studded Halter Triangle Bikini Swimsuit',10.99,97),
    ('ROMWE Floral Print Contrast Mesh Skirt',5.00,56),
    ('SHEIN ICON Zipper Front Ruffle Trim Flare Leg Pants',22.49,67),
    ('Bead Decor Face Covering Chain',2.25,39),
    ('Color Block Beaded Face Covering Chain',2.30,15),
    ('SHEIN SXY Tie Dye Print Mesh Leggings',10.99,50),
    ('Rhinestone & Flower Decor Face Covering',2.40,6),
    ('Rhinestone Decor Face Covering',1.00,14),
    ('3pack Plain Halter Bikini Swimsuit & Kimono',17.00,6),
    ('Snakeskin Ring Linked Plunging One Piece Swimsuit',12.49,1),
    ('Bikinx Halter Triangle Bikini Swimsuit With Ombre Cover Up',11.99,5),
    ('SHEIN ICON Hook And Eye Crop PU Leather Top & Key-holder Strap Hem Skirt',7.00,16),
    ('SHEIN SXY Solid Mermaid Hem Skirt',10.00,77),
    ('2pcs Beaded Face Covering Chain',2.30,20),
    ('Minimalist Face Covering Chain',1.50,52),
    ('Wide Waistband Biker Shorts',6.49,39),
    ('10pcs Solid Face Covering',1.80,77),
    ('Striped Halter Bikini Swimsuit',5.25,38),
    ('Ribbed Triangle Tie Side Bikini Swimsuit',6.99,47),
    ('Plain Tie Side Thong One Piece Swimsuit',11.99,63),
    ('Solid Face Covering',1.30,68),
    ('Ditsy Floral Print Bow Front Triangle Thong Bikini Swimsuit',7.49,30),
    ('ROMWE Solid Ruffle Hem Skirt',6.75,62),
    ('SHEIN PETITE Floral & Heart Print Flare Leg Pants',12.99,50),
    ('Rhinestone Decor Face Covering',1.00,65),
    ('Faux Pearl Decor Face Covering Chain',2.40,8),
    ('SHEIN Frenchy Button Detail Zip Side PU Shorts',11.49,67),
    ('3pcs Solid Face Covering',1.50,37),
    ('Color Block Triangle Thong Bikini Swimsuit',11.00,88),
    ('Shirred Plunging Crisscross Back One Piece Swimsuit',11.99,31),
    ('3pack Random Floral Print Halter Bikini Swimsuit & Beach Skirt',12.99,17),
    ('High Waist Asymmetrical Hem Knot Front Skirt',6.75,97),
    ('Geo Print Knot Front Pants',10.49,45),
    ('2pcs Beaded Face Covering Chain',2.40,49),
    ('Minimalist Face Covering Chain',2.00,1),
    ('Paper Bag Waist Knot Front Shorts',8.49,34),
    ('Rhinestone & Flower Decor Face Covering',2.10,42),
    ('6pcs Solid Face Covering',3.70,99),
    ('Triangle Thong Bikini Swimsuit',6.25,84),
    ('Plain Criss Cross Cut-out Bikini Top',7.00,27),
    ('Plain Cross Cut-out One Piece Swimsuit',9.49,21),
    ('SHEIN Slit Hem Lace Pencil Skirt',9.75,25),
    ('O-ring Detail Tie Backless Halter Triangle High Cut Bikini Swimsuit',7.00,6),
    ('SHEIN SXY Solid Knot Side Wrap Hem Skirt',9.00,29),
    ('Random Flower Decor Beaded Face Covering Chain',2.60,22),
    ('Tie Dye Halter Triangle Bikini Swimsuit With Cover Up',15.49,53),
    ('Butterfly Decor Beaded Face Covering Chain',2.80,19),
    ('MOTF PREMIUM VISCOSE FLORAL LINE FLOWY SKIRT',25.25,15),
    ('SHEIN Frenchy Allover Floral Print Ruffle Hem Skirt',12.49,84),
    ('Neon Lime Ring Linked High Cut Bikini Swimsuit With Cover Up',16.49,13),
    ('3pcs Bead Decor Face Covering Chain',2.00,51),
    ('Leopard Lace Halter Triangle Tie Side Bikini Swimsuit',10.49,72),
    ('Plain Criss Cross One Piece Swimsuit With Beach Skirt',14.00,91),
    ('Striped Strap Halter Triangle Bikini Swimsuit',7.49,39),
    ('ROMWE Striped Button Front Skirt',6.25,7),
    ('SHEIN X Vibrant Dames Drawstring Waist Velvet Pants',18.49,93),
    ('2pcs Beaded Face Covering Chain',2.50,5),
    ('Minimalist Face Covering Chain',1.50,44),
    ('SHEIN EZwear Allover Print Flare Leg Pants',6.00,39),
    ('Rhinestone Decor Face Covering',3.50,9),
    ('Allover Print Halter Triangle Bikini Swimsuit With Cover Up',12.49,63),
    ('Mesh Insert Criss Cross One Piece Swimsuit',16.99,98),
    ('Plain Halter Bikini Swimsuit',11.00,51),
    ('Tie Dye Halter Triangle Bikini Swimsuit & Beach Skirt',15.49,44),
    ('SHEIN Frenchy High Waist Belted Flare Leg Pants',10.00,10),
    ('SHEIN Ditsy Floral Layered Hem Belted Shorts',7.75,80),
    ('SHEIN SXY Drawstring Waist Flap Pocket Side Cargo Pants',22.49,6),
    ('6pcs Solid Face Covering',5.90,43),
    ('Ladybug Decor Face Covering Chain',2.10,96),
    ('Floral Print Layered Skirt',5.50,35),
    ('DAZY High Waist Pleated Detail Skirt Without Belt',13.99,72),
    ('2pcs Cat Pattern Face Covering',2.10,39),
    ('Floral Triangle Tie Side Bikini Swimsuit',6.25,99),
    ('Ditsy Floral Print Smocked Tie Back Halter Bikini Swimsuit',11.00,66),
    ('SHEIN ICON Solid Zipper Fly Wide Leg Pants',11.00,58),
    ('Striped Tanga Bikini Swimsuit',5.75,58),
    ('ROMWE Skeleton Patched Gingham Frill Trim Skirt',6.00,87),
    ('10pcs Floral Pattern Disposable Face Covering',1.50,47),
    ('Solid High Waist Skirt',11.49,73),
    ('Solid Face Covering',1.20,80),
    ('MOTF PREMIUM ACETATE CHAIN BELT SKIRT',21.00,66),
    ('Flower Decor Face Covering Chain',2.50,52),
    ('2pcs Star & Faux Pearl Decor Face Covering Chain',2.90,27),
    ('SHEIN BIZwear Solid Ruffle Hem Skirt',9.99,96),
    ('Halloween Pumpkin Patch Decor Face Covering',1.50,69),
    ('3pcs Solid Face Covering',4.00,19),
    ('Letter Decor Chain Linked Halter Bikini Swimsuit',11.49,11),
    ('Backless Cross Back Cut-out One Piece Swimsuit',8.98,14),
    ('Allover Print Halter Triangle Bikini Swimsuit',6.49,37),
    ('ROMWE Graphic Mini Skirt',4.50,42),
    ('2pcs Rhinestone Decor Disposable Face Covering',1.50,27),
    ('High Waist PU Pants',16.00,97),
    ('Rhinestone Letter Decor Face Covering',2.40,65),
    ('5pcs Face Covering Adjustment Rope',1.50,94),
    ('Bead Decor Face Covering Chain',3.70,96),
    ('Allover Floral Print Straight Leg Pants',9.25,3),
    ('High Waist Lace Pants Without Panty',13.00,66),
    ('2pcs Rhinestone Skull Decor Face Covering',2.10,96),
    ('MOTF PREMIUM LINEN BERMUDA SHORTS',22.25,44),
    ('Bikinx Tie Backless Halter Triangle Bikini Swimsuit With Beach Skirt',10.49,90),
    ('Cross Back Push Up One Piece Swimsuit',13.99,59),
    ('Christmas Tree Embroidered Face Covering',1.50,82),
    ('Textured Triangle Thong Bikini Swimsuit',11.49,21),
    ('Floral and Banana Print Split Thigh Skirt',7.00,64),
    ('Dazy-Less Elastic Waist Flare Leg Pants',7.25,75),
    ('SHEIN ICON Cut Out Waist Lace Flare Leg Pants Without Panty',10.99,30),
    ('2pcs Geometric Face Covering Chain',3.60,36),
    ('Butterfly & Faux Pearl Decor Face Covering Chain',2.00,49),
    ('Lightning & Slogan Graphic Straight Leg Chambray Pants',8.00,95),
    ('SHEIN BAE Twist Front Ruched Bodycon Skirt',9.49,44),
    ('10pcs Heart Pattern Face Covering',1.50,3),
    ('Zebra Striped Triangle Bikini Top',5.49,44),
    ('Cut-out Cross Halter One Piece Swimsuit',13.49,11),
    ('3pack Plain Halter Triangle Bikini Swimsuit & Cover Up Bodysuit',15.49,56),
    ('ROMWE Floral Print Split Skirt',5.25,91),
    ('SHEIN EZwear Allover Print Flare Leg Pants',11.99,4),
    ('Faux Pearl Decor Face Covering Chain',1.70,39),
    ('Solid Face Covering',1.80,28),
    ('Butterfly & Faux Pearl Decor Face Covering Chain',2.00,57),
    ('Letter Graphic Colorblock Shorts',9.00,94),
    ('2pcs Solid Face Covering',1.50,32),
    ('Rib Frill Trim Tie Back Bikini Swimsuit',13.49,42),
    ('Criss Cross Backless One Piece Swimsuit',11.99,46),
    ('Fuzzy Trim Lace Up Side Tie Backless Halter One Piece Swimsuit',12.00,83),
    ('SHEIN Solid Drawstring Slit Hem Wide Leg Pants',9.50,54),
    ('ROMWE Ditsy Floral Shirred Skirt',5.00,82),
    ('SHEIN X Kovid Kapoor Solid Fold Pleated Skirt',24.49,92),
    ('Random Rhinestone Decor Face Covering',3.10,93),
    ('Butterfly & Faux Pearl Decor Face Covering Chain',2.00,51),
    ('DAZY Solid Flare Leg Pants',22.49,57),
    ('Striped Face Covering & Twist Detail Hair Band & Scrunchie',2.40,15),
    ('Cut Out Triangle High Waisted Bikini Swimsuit',11.49,71),
    ('Palm Leaf Print Criss Cross Halter Bikini Swimsuit',8.38,75),
    ('Plain Thong Bikini Swimsuit',8.49,29),
    ('SHEIN Foldover Waist Solid Shorts',6.75,65),
    ('SHEIN VCAY Floral Print Belted Wide Leg Pants',13.49,39),
    ('Animal Pattern Face Covering With Chain',2.80,85),
    ('Heart & Faux Pearl Decor Face Covering Chain',1.90,11),
    ('DAZY Solid Elastic Waist Straight Leg Pants',18.75,49),
    ('2pcs Rhinestone Decor Face Covering',1.70,78),
    ('3pack Halter Triangle Bikini Swimsuit & Cover Up',14.99,55),
    ('Christmas Stocking Patch Decor Face Covering',1.50,42),
    ('Cross Backless One Piece Swimsuit',10.49,46),
    ('SHEIN X Ultra Metallic Halter Triangle Bikini Swimsuit',8.00,72),
    ('ROMWE Plaid Print A Line Skirt',5.00,59),
    ('SHEIN X Katalyst Kouture Drawstring Front Drop Crotch Parachute Pants',17.99,91),
    ('Solid Face Covering With Earmuffs',2.30,40),
    ('Heart & Faux Pearl Decor Face Covering Chain',1.90,38),
    ('SHEIN EZwear Flap Pocket Side Drawstring Waist Cargo Pants',16.99,19),
    ('Cartoon Cat & Crown Embroidered Face Covering',2.20,19),
    ('Floral Print Triangle Bikini Swimsuit & Bandana',11.00,4),
    ('Criss Cross Ruched High Waisted Bikini Swimsuit',13.49,27),
    ('Striped Halter Triangle Bikini Swimsuit',10.49,86),
    ('SHEIN Marble Print Ruched Bodycon Skirt',3.75,33),
    ('SHEIN ICON Grommet Lace Up Detail Flare Leg Pants',16.99,31),
    ('4pcs Christmas Elk & Bell Pattern Face Covering',2.80,90),
    ('Marble Print Bikini Swimsuit  With Beach Skirt & Bandana',14.49,22),
    ('Flower & Star Charm Face Covering Chain',2.10,99),
    ('High Waist Plicated Detail Shorts',5.50,18),
    ('Two Tone Fuzzy Face Covering',2.60,49),
    ('3pack Butterfly Print Triangle Bikini Swimsuit & Beach Skirt',12.49,50),
    ('Tropical Print Lace Up Backless Drawstring Side Sports Set',15.00,29),
    ('Two Tone Wrap Detail Bikini Swimsuit',12.00,89),
    ('Spaghetti Underwired High Cut Bikini Swimsuit',8.00,55),
    ('ROMWE Solid Tiered Skirt',5.50,67),
    ('SHEIN EZwear Letter Graphic Biker Shorts',4.99,42),
    ('10pcs Heart Pattern Disposable Face Covering',2.00,46),
    ('Flower & Faux Pearl Decor Face Covering Chain',2.10,45),
    ('DAZY High Waist Mermaid Hem Skirt',18.99,35),
    ('Holographic Face Covering & Scrunchie',1.90,87),
    ('Two Tone Heart Print Triangle Tie Side Bikini Swimsuit',6.88,15),
    ('Solid Cross Back One Piece Swimsuit',8.49,86),
    ('Colorblock Halter Triangle Bikini Swimsuit',10.00,14),
    ('Knot Side Cut Out Split Hem Chiffon Skirt',6.00,34),
    ('SHEIN EZwear Plaid Print Mermaid Hem Skirt',11.49,74),
    ('Heart Decor Face Covering Chain',2.50,12),
    ('Christmas Santa Claus & Tree Decor Face Covering Chain',2.20,61),
    ('SHEIN ICON Solid Flare Leg Pants',14.49,96),
    ('Tie Dye Face Covering',1.60,62),
    ('Ditsy Floral Print Smocked Tie Side Bikini Swimsuit',11.49,72),
    ('Colorblock Cut Out Tie Back Underwire One Piece Swimsuit',11.99,14),
    ('Solid Lace Up Halter Triangle Bikini Swimsuit',10.00,47),
    ('ROMWE Lace Up Pleated Skirt',6.00,65),
    ('SHEIN BAE Ruffle Hem Solid Skirt',7.49,39),
    ('5pcs Christmas Tree Pattern Face Covering',2.80,26),
    ('Star Decor Beaded Face Covering Chain',1.90,91),
    ('DAZY High Waist Tulip Hem Skirt',11.00,46),
    ('Tie Dye Face Covering',1.60,4),
    ('Contrast Binding Triangle Tie Side Bikini Swimsuit',10.49,17),
    ('Open Back Self Tie One Piece Swimsuit',12.00,67),
    ('Plain Tie Shoulder Cut-out Bikini Swimsuit',8.50,95),
    ('Topstitching Wideband Waist Flare Skirt',5.75,86),
    ('MOTF PREMIUM BELTED BUCKLE SUIT PANTS WITHOUT BELT',34.99,90),
    ('2pcs Leopard Pattern Face Covering',2.10,62),
    ('Heart & Faux Pearl Decor Face Covering Chain',2.00,61),
    ('SHEIN VCAY Ditsy Floral Drawstring Ruffle Hem Skirt',10.49,28),
    ('3pcs Color Block Face Covering Chain',2.40,79),
    ('Contrast Binding Triangle Tie Side Bikini Swimsuit',8.00,1),
    ('Swiss Dot Bishop Sleeve Blouse',5.68,86),
    ('Lace Up Triangle Bikini Top',5.49,26),
    ('ROMWE Graphic Straight Skirt',5.00,9),
    ('SHEIN ICON Drawstring Side Lace Bodycon Skirt',8.49,11),
    ('Cartoon Dinosaur Decor Face Covering Chain',2.60,50),
    ('Bead Decor Face Covering Chain',2.60,98),
    ('Solid Ruffle Trim Wrap Skort',10.49,47),
    ('2pcs Cartoon Animal Design Face Covering',3.40,6),
    ('ROMWE Sweetness X Gabiciamp Butterfly Decor Triangle Halter Tie Side Bikini Swimsuit',9.49,41),
    ('SHEIN EZwear Solid High Waist Leggings',8.49,55),
    ('Striped Print Triangle Bikini Swimsuit',7.00,65),
    ('ROMWE Satin Layered Hem Skirt',5.50,17),
    ('Halter Triangle Tie Side Bikini Swimsuit',8.80,81),
    ('SHEIN EZwear Letter Graphic Two Tone Shorts',11.49,33),
    ('3pcs Soccer & Basketball Pattern Face Covering',2.30,63),
    ('2pcs Minimalist Face Covering Chain',2.80,26),
    ('SHEIN SXY Cut Out Waist Flare Leg Pants',4.99,7),
    ('Leopard Print Face Covering',1.50,62),
    ('Water Color Triangle Bikini Top',4.49,17),
    ('Solid Batwing Sleeve Blouse',7.00,15),
    ('3pack Butterfly Print Triangle Bikini Swimsuit & Bandana',11.49,62),
    ('Fringe Hem Knot Front Skirt',7.00,5),
    ('SHEIN X Kovid Kapoor Flap Pocket Side Wide Leg Pants',32.99,66),
    ('2pcs Camo Pattern Face Covering',1.70,27),
    ('Triangle Decor Face Covering Chain',2.20,30),
    ('Twist Front Glitter Leggings',11.49,38),
    ('10pcs Star Pattern Disposable Face Covering',2.20,67),
    ('Allover Print Halter Triangle Bikini Swimsuit',11.49,19),
    ('SHEIN VCAY Tie Front Split Hem Dress',19.00,64),
    ('Allover Print Knot Side Bikini Swimsuit',9.49,12),
    ('SHEIN X Abrar Zenkawi Figure Graphic Belted Skirt',11.25,29),
    ('4pcs Sequin Decor Face Covering',2.50,46),
    ('SHEIN VCAY Ditsy Floral Split Hem Skirt',5.49,64),
    ('Graphic Print Halter Triangle Bikini Swimsuit',8.49,54),
    ('Palette Decor Face Covering Chain',2.60,24),
    ('Minimalist Face Covering Chain',2.10,25),
    ('Allover Floral Print Split Thigh Ruched Detail Skirt',11.49,9),
    ('2pcs Rhinestone Decor Face Covering',1.50,29),
    ('SHEIN X Peartree Stories Geo Print Maxi Skirt',9.22,46);
